name = "jpapp-tts-proxy"
main = "worker/google-tts.js"
compatibility_date = "2024-03-20"
preview_urls = true

# Configure secrets via `wrangler secret put`, e.g. GOOGLE_API_KEY, CLIENT_TOKEN

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "79138047540a434c84132753f4e1b2df"

[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimiter"]